### ISSUE TITLE
opencv  version?

### ISSUE THREAD

**Issue by yangyuke001** [yangwangx/denseFlow_gpu#1]
I got  the error:
error while loading shared libraries: libopencv_gpu.so.2.4: cannot open shared object file: No such file or directory

my environment:
ubuntu18.04
opencv 3.4.0

**Comment by yangwangx** [comment]
The source code `denseFlow_gpu.cpp` uses `opencv2` headers.
You can definitely change the code to use `opencv3` headers.

``` cpp
#include "opencv2/video/tracking.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/gpu/gpu.hpp"
```

**Comment by yangyuke001** [comment]
@yangwangx 
Thanks

**Comment by GayatriPurandharT** [comment]
I got the same error: 

> error while loading shared libraries: libopencv_gpu.so.2.4: cannot open shared object file: No such file or directory

Changing opencv2 libraries to opencv3 did not work in my case. I still get the same error. Help would be greatly appreciated.
Thanks
